### PR TITLE
Update unicorn in gemspec

### PR DESCRIPTION
**Pull request by zhuravel**
Unicorn 6.0 was released on 2021-03-17:
https://yhbt.net/unicorn/NEWS.html

This release patches a rare security vulnerability:
https://github.blog/2021-03-18-how-we-found-and-fixed-a-rare-race-condition-in-our-session-handling/

Changelog since version 5.8.0:
https://github.com/defunkt/unicorn/compare/v5.8.0...v6.0.0

### CODE REVIEW

**Comment by henrik** [comment]
@zhuravel Have you found that things work fine by just bumping this constraint and leaving unicorn-worker-killer otherwise as-is?

**Comment by zhuravel** [comment]
@henrik Yes, we have this in our Gemfile:
```ruby
gem 'unicorn', '~> 6'
gem 'unicorn-worker-killer', github: 'kzk/unicorn-worker-killer', ref: 'refs/pull/74/head'

**Comment by henrik** [comment]
@zhuravel Nice, thank you. We've done the same since around the time of my question above (well, we forked the gem instead and applied the change) and so far so good. 👍

**Comment by kzk** [comment]
@zhuravel Thank you for the PR! It's merged and the new version was published on rubygems.

**Pull request merged**
