### PR TITLE
Require 'unicorn' library

### PR DESCRIPTION
**Pull request by faizalzakaria**
`Unicorn-worker-killer` is using Unicorn::HttpServer. We need unicorn library prio to this call.

### CODE REVIEW

**Comment by 007** [comment]
@kzk @jclem any chance of getting this merged / released? I'm seeing this failure for a blank `config.ru` with just `require 'unicorn/worker_killer'`, but it works if I add `require 'unicorn'` before the `worker_killer` line.

**Comment by faizalzakaria** [comment]
Any update on this @kzk ? I can rebase if needed.

**Comment by jclem** [comment]
@007 I'm no longer maintaining this (not running any Ruby anywhere at the moment), it's all @kzk AFAIK.

**Comment by kzk** [comment]
@007 @jclem I'll take a look at this on this weekend!

**Pull request closed without merging**
